// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertBook(arg1, arg2) {
  return window['go']['main']['App']['ConvertBook'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function SelectEpub() {
  return window['go']['main']['App']['SelectEpub']();
}
