// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertBook(arg1:string,arg2:string):Promise<main.ConversionProgress>;

export function GetLogsSince(arg1:number):Promise<Record<string, any>>;

export function SelectEpub():Promise<string>;
